x-postgres-env: &postgres-env
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}

services:
  init-dirs:
    image: busybox
    command: sh -c "mkdir -p /mnt/postgres/data && tail -f /dev/null"
    volumes:
      - .:/mnt
    restart: "no"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      <<: *postgres-env
    volumes:
      - type: bind
        source: ./postgres/data
        target: /var/lib/postgresql/data
        bind:
          selinux: z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - init-dirs

  init-db:
    build:
      context: .
      dockerfile: containers/containerfiles/backend.containerfile
    command: python seed.py
    volumes:
      - ./backend:/app:z
      - ./postgres/default_data:/scripts:z
    environment:
      <<: *postgres-env
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  backend:
    build:
      context: .
      dockerfile: containers/containerfiles/backend.containerfile
    volumes:
      - ./backend:/app:z
      - ./backend/requirements.default:/app/requirements.txt:z
    environment:
      <<: *postgres-env
      HOST: ${BACKEND_HOST:-0.0.0.0}
      PORT: ${BACKEND_PORT:-8000}
      EXPIRES_IN: ${EXPIRES_IN:-10800}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      RELOAD: ${RELOAD:-false}
      WORKERS: ${WORKERS:-1}
      ACCESS_LOG: ${ACCESS_LOG:-true}
      LIFESPAN: ${LIFESPAN:-auto}
      HTTP: ${HTTP:-h11}
      WS: ${WS:-auto}
      PROXY_HEADERS: ${PROXY_HEADERS:-true}
      FORWARDED_ALLOW_IPS: ${FORWARDED_ALLOW_IPS:-*}
      LIMIT_MAX_REQUESTS: ${LIMIT_MAX_REQUESTS:-}
    depends_on:
      postgres:
        condition: service_healthy
  web:
    build:
      context: .
      dockerfile: containers/containerfiles/frontend.containerfile
    profiles: ["PROD"]
    environment:
      BACKEND_URL: ${BACKEND_URL:-http://backend:8000}
    depends_on:
      - backend
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.access-control-service.entrypoints=websecure"
      - "traefik.http.routers.access-control-service.rule=Host(`${HOST:-localhost}`) && PathPrefix(`/access-control-service`)"
      - "traefik.http.routers.access-control-service.tls.certresolver=myresolver"
      - "traefik.http.middlewares.access-control-service-strip.stripprefix.prefixes=/access-control-service"
      - "traefik.http.routers.access-control-service.middlewares=access-control-service-strip"
      - "traefik.http.services.access-control-service.loadbalancer.server.port=80"

networks:
  web:
    external: true